version: '3'

services:

  node:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    image: node-image
    container_name: nodejs
    networks:
      - nodenet
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - node

  db:
    image: mysql:8.0
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge